# Generated by Django 4.2.7 on 2023-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userPrivacy',
            field=models.BooleanField(default=True),
        ),
    ]
