# Generated by Django 4.2.7 on 2023-12-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_users_userprivacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userScore', models.IntegerField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='userPassword',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='userEmail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='userName',
            field=models.CharField(default='', max_length=150),
        ),
    ]
