# Generated by Django 4.2.7 on 2023-12-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_box_performance_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Box',
        ),
    ]
