# Generated by Django 4.2.7 on 2023-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_card_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
