# Generated by Django 4.2.7 on 2023-12-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_card_id_remove_card_link_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='paired',
        ),
    ]
