# Generated by Django 4.2.7 on 2023-12-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_card_paired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
